apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-2-hw-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-2-hw
  template:
    metadata:
      labels:
        app: k8s-2-hw
    spec:
      containers:
      - name: app
        image: k8s_2:v18
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 8000
