apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-3-hw-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-3-hw
  template:
    metadata:
      labels:
        app: k8s-3-hw
    spec:
      containers:
      - name: app
        image: ninib/k8s_3:latest
        resources:
          limits:
            memory: "80Mi"
            cpu: "150m"
        ports:
        - containerPort: 8080
        # см https://habr.com/ru/company/flant/blog/470958/
        # livenessProbe:
        #   httpGet:
        #     port: 8080
        #     path: /
        #   initialDecaySeconds: 10
        #   periodSeconds: 5
        #   timeoutSeconds: 2
        readinessProbe:
          httpGet:
            port: 8080
            path: /health
          initialDelaySeconds: 10
          periodSeconds: 5
          

