apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: k8s-3-hw
build:
  artifacts:
  - image: ninib/k8s_3
    context: flask_app
deploy:
  kubectl:
    manifests:
    - deployment/deployment.yaml
    - deployment/ingress.yaml
    - deployment/service.yaml
